package jdbcgui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

public class AddNewEvent extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    LoginUser luser;

    /**
     * Creates new form UpdateDeleteDepartment
     * @param user
     */
    public AddNewEvent(LoginUser user) {
        initComponents();
        this.setLocationRelativeTo(null); // center
        luser = user;

        // set all error labels to invisible
        dbCon = new myDBCon();
        clearErrorLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEventidError = new javax.swing.JLabel();
        txtLoc = new javax.swing.JTextField();
        lblNameError = new javax.swing.JLabel();
        lblLocError = new javax.swing.JLabel();
        txtEventid = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        lblDateError = new javax.swing.JLabel();
        lblTimeError = new javax.swing.JLabel();
        btnAddNewDepartment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Event");

        txtName.setBackground(new java.awt.Color(242, 242, 242));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Event Name"));

        lblEventidError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblEventidError.setForeground(new java.awt.Color(255, 0, 0));
        lblEventidError.setText("error label");

        txtLoc.setBackground(new java.awt.Color(242, 242, 242));
        txtLoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Event Location"));

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        lblLocError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblLocError.setForeground(new java.awt.Color(255, 0, 0));
        lblLocError.setText("error label");

        txtEventid.setBackground(new java.awt.Color(242, 242, 242));
        txtEventid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEventid.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Event ID"));

        txtDate.setBackground(new java.awt.Color(242, 242, 242));
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Event Date"));

        txtTime.setBackground(new java.awt.Color(242, 242, 242));
        txtTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTime.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Event Time"));

        lblDateError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDateError.setForeground(new java.awt.Color(255, 0, 0));
        lblDateError.setText("error label");

        lblTimeError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblTimeError.setForeground(new java.awt.Color(255, 0, 0));
        lblTimeError.setText("error label");

        btnAddNewDepartment.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewDepartment.setText("Add New");
        btnAddNewDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEventid, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEventidError, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLocError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEventid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventidError))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeError))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewDepartment)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDepartmentActionPerformed
        // verify input data
        // verify that new user does not currently exist
        // if all validations are successful then enter the new user
        try {

            clearErrorLabels();
            if (isValidData()) {

                String prepSQL = "INSERT INTO event (eventid, name, loc, \"Date\", time) VALUES ('"
                        + txtEventid.getText().trim() + "', '"
                        + txtName.getText().trim() + "', '"
                        + txtLoc.getText().trim() + "', '"
                        + txtDate.getText().trim() + "', '"
                        + txtTime.getText().trim() + "')";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    
                    String action = "Event " + txtEventid.getText().trim() + " has been added.";
                    updateLogs(action);

                    javax.swing.JLabel label = new javax.swing.JLabel("New event added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    //clearInputBoxes();
                }

                // rs.close();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new event.");
        }
    }//GEN-LAST:event_btnAddNewDepartmentActionPerformed

    private void clearErrorLabels() {
        lblEventidError.setText("");
        lblNameError.setText("");
        lblLocError.setText("");
        lblDateError.setText("");
        lblTimeError.setText("");
    }

    private boolean isInteger(String s) {
        try {
            Integer.valueOf(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    private static boolean isValidDate(String dateString) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yy", Locale.ENGLISH);
        dateFormat.setLenient(false); // this will not allow dates like "32-MAR-00"

        try {
            dateFormat.parse(dateString.trim());
            return true;
        } catch (ParseException pe) {
            return false;
        }
    }

    private boolean isDuplicateEventID(String eventid) {
        boolean result = false;  // Assume no duplicate exists
        try {
            dbCon = new myDBCon();
            ResultSet newrs;
            // The deptid should be parameterized to prevent SQL injection
            String query = "SELECT * FROM event WHERE eventid = ?";
            PreparedStatement pstmt = dbCon.prepareStatement(query);
            pstmt.setString(1, eventid);
            newrs = pstmt.executeQuery();

            // If newrs.isBeforeFirst() is true, there are rows, hence a duplicate exists
            if (newrs.isBeforeFirst()) {
                result = true;  // There is a duplicate
            }
            newrs.close();
            pstmt.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        return result;
    }

    private void updateLogs(String action) {
        try {
            String prepSQL = "INSERT INTO log VALUES (?,?,?,SYSTIMESTAMP)";
            PreparedStatement preparedStatement = dbCon.prepareStatement(prepSQL);
            preparedStatement.setInt(1, luser.userid);
            preparedStatement.setString(2, luser.username);
            preparedStatement.setString(3, action);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error inserting the logs.");
        }
    }

    private boolean isValidData() throws SQLException {
        clearErrorLabels();
        boolean result = true;

        String eventId = txtEventid.getText().trim();
        String name = txtName.getText().trim();
        String location = txtLoc.getText().trim();
        String time = txtTime.getText().trim();
        String date = txtDate.getText().trim();
    
        if (eventId.isEmpty() || !isInteger(eventId) || isDuplicateEventID(eventId)) {
            lblEventidError.setText(eventId.isEmpty() ? "Required." : !isInteger(eventId) ? "Must be an integer." : "This EventID already exists.");
            lblEventidError.setVisible(true);
            result = false;
        }

        if (name.isEmpty() || name.length() > 30) {
            lblNameError.setText(name.isEmpty() ? "Required." : "Must be < 30 chars.");
            lblNameError.setVisible(true);
            result = false;
        }
    
        if (location.isEmpty() || location.length() > 30) {
            lblLocError.setText(location.isEmpty() ? "Required." : "Must be < 30 chars.");
            lblLocError.setVisible(true);
            result = false;
        }
    
        if (time.isEmpty() || time.length() > 20) {
            lblTimeError.setText(time.isEmpty() ? "Required." : "Must be < 20 chars.");
            lblTimeError.setVisible(true);
            result = false;
        }
    
        if (date.isEmpty() || !isValidDate(date)) {
            lblDateError.setText(date.isEmpty() ? "Required." : "Must be in dd-MMM-yy format.");
            lblDateError.setVisible(true);
            result = false;
        }
    
        return result;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblEventidError;
    private javax.swing.JLabel lblLocError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblTimeError;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEventid;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
