package jdbcgui;

public class Menu extends javax.swing.JFrame {

    LoginUser luser; // the login user details are obtained from the Login form

    /**
     * Creates new form Menu
     */
    public Menu(LoginUser user) {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        this.getContentPane().setBackground(new java.awt.Color(238, 242, 243));

        luser = user; // user details are obtained from the Login form and passed to constructor of Menu form object

        if (user.type == 2) { // if student
            jMenuItem11.setText("View Organized Events");
            this.setTitle("Menu - Student");
            jMenuItem7.setVisible(false);
            menuAddDepartments.setVisible(false);
            menuUpdateDepartments.setVisible(false);
            menuUpdateEvents.setVisible(false);
            menuAddEvents.setVisible(false);
            jMenuItem12.setVisible(false);
            
        }

        if (user.type == 1) { // if professor
            this.setTitle("Menu - Professor");
        }

        if (user.type != 0) { // if not admin
            menuLog.setVisible(false);
            menuAddUsers.setVisible(false);
            
            menuUpdateUsers.setText("View Users");
            menuUpdateAdmins.setText("View Admins");
            menuUpdateProfessors.setText("View Professors");
            menuUpdateStudents.setText("View Students");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        menuAddUsers = new javax.swing.JMenu();
        menuAddAdmin = new javax.swing.JMenuItem();
        menuAddProfessor = new javax.swing.JMenuItem();
        menuAddStudent = new javax.swing.JMenuItem();
        menuUpdateUsers = new javax.swing.JMenu();
        menuUpdateAdmins = new javax.swing.JMenuItem();
        menuUpdateProfessors = new javax.swing.JMenuItem();
        menuUpdateStudents = new javax.swing.JMenuItem();
        menuDepartment = new javax.swing.JMenu();
        menuViewDepartments = new javax.swing.JMenuItem();
        menuAddDepartments = new javax.swing.JMenuItem();
        menuUpdateDepartments = new javax.swing.JMenuItem();
        menuEvent = new javax.swing.JMenu();
        menuViewEvents = new javax.swing.JMenuItem();
        menuAddEvents = new javax.swing.JMenuItem();
        menuUpdateEvents = new javax.swing.JMenuItem();
        menuOrganize = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuRegister = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuLog = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - Admin");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/employees.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(238, 242, 243));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuFile.add(menuLogout);

        menuExit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuUser.setText("User");
        menuUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuAddUsers.setText("Add New User ");
        menuAddUsers.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuAddAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuAddAdmin.setText("Add New Admin");
        menuAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddAdminActionPerformed(evt);
            }
        });
        menuAddUsers.add(menuAddAdmin);

        menuAddProfessor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuAddProfessor.setText("Add New Professor");
        menuAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProfessorActionPerformed(evt);
            }
        });
        menuAddUsers.add(menuAddProfessor);

        menuAddStudent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuAddStudent.setText("Add New Student");
        menuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddStudentActionPerformed(evt);
            }
        });
        menuAddUsers.add(menuAddStudent);

        menuUser.add(menuAddUsers);

        menuUpdateUsers.setText("Update/Delete User");
        menuUpdateUsers.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuUpdateAdmins.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuUpdateAdmins.setText("Update/Delete Admin");
        menuUpdateAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateAdminsActionPerformed(evt);
            }
        });
        menuUpdateUsers.add(menuUpdateAdmins);

        menuUpdateProfessors.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuUpdateProfessors.setText("Update/Delete Professor");
        menuUpdateProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateProfessorsActionPerformed(evt);
            }
        });
        menuUpdateUsers.add(menuUpdateProfessors);

        menuUpdateStudents.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuUpdateStudents.setText("Update/Delete Student");
        menuUpdateStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateStudentsActionPerformed(evt);
            }
        });
        menuUpdateUsers.add(menuUpdateStudents);

        menuUser.add(menuUpdateUsers);

        jMenuBar1.add(menuUser);

        menuDepartment.setText("Department");
        menuDepartment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuViewDepartments.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuViewDepartments.setText("View Departments");
        menuViewDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewDepartmentsActionPerformed(evt);
            }
        });
        menuDepartment.add(menuViewDepartments);

        menuAddDepartments.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuAddDepartments.setText("Add Department");
        menuAddDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddDepartmentsActionPerformed(evt);
            }
        });
        menuDepartment.add(menuAddDepartments);

        menuUpdateDepartments.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuUpdateDepartments.setText("Update/Delete Department");
        menuUpdateDepartments.setToolTipText("");
        menuUpdateDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateDepartmentsActionPerformed(evt);
            }
        });
        menuDepartment.add(menuUpdateDepartments);

        jMenuBar1.add(menuDepartment);

        menuEvent.setText("Event");
        menuEvent.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        menuViewEvents.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuViewEvents.setText("View Events");
        menuViewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewEventsActionPerformed(evt);
            }
        });
        menuEvent.add(menuViewEvents);

        menuAddEvents.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuAddEvents.setText("Add Event");
        menuAddEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddEventsActionPerformed(evt);
            }
        });
        menuEvent.add(menuAddEvents);

        menuUpdateEvents.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        menuUpdateEvents.setText("Update/Delete Event");
        menuUpdateEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateEventsActionPerformed(evt);
            }
        });
        menuEvent.add(menuUpdateEvents);

        jMenuBar1.add(menuEvent);

        menuOrganize.setText("Organize");
        menuOrganize.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem7.setText("Organize new event");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuOrganize.add(jMenuItem7);

        jMenuItem11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem11.setText("Update/Delete an organized event");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuOrganize.add(jMenuItem11);

        jMenuBar1.add(menuOrganize);

        menuRegister.setText("Register");
        menuRegister.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem9.setText("Register in an event");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuRegister.add(jMenuItem9);

        jMenuItem12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem12.setText("Update/Delete Registration");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuRegister.add(jMenuItem12);

        jMenuBar1.add(menuRegister);

        menuLog.setText("Log");
        menuLog.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem10.setText("View log");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuLog.add(jMenuItem10);

        jMenuBar1.add(menuLog);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuUpdateDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateDepartmentsActionPerformed
        (new UpdateDeleteDepartment(luser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateDepartmentsActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        (new OrganizeEvent(luser)).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        (new UpdateDeleteAnOrganizedEvent(luser)).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        (new RegisterInEvent(luser)).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        (new ManageRegistration(luser)).setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        (new ViewLog()).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuAddDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddDepartmentsActionPerformed
        (new AddNewDepartment(luser)).setVisible(true);
    }//GEN-LAST:event_menuAddDepartmentsActionPerformed

    private void menuViewDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewDepartmentsActionPerformed
        (new ViewDepartments()).setVisible(true);
    }//GEN-LAST:event_menuViewDepartmentsActionPerformed

    private void menuViewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewEventsActionPerformed
        (new ViewEvents()).setVisible(true);
    }//GEN-LAST:event_menuViewEventsActionPerformed

    private void menuAddEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddEventsActionPerformed
        (new AddNewEvent(luser)).setVisible(true);
    }//GEN-LAST:event_menuAddEventsActionPerformed

    private void menuUpdateEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateEventsActionPerformed
        (new UpdateDeleteEvent(luser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateEventsActionPerformed

    private void menuAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddAdminActionPerformed
        (new AddNewAdmin(luser)).setVisible(true);
    }//GEN-LAST:event_menuAddAdminActionPerformed

    private void menuAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProfessorActionPerformed
        (new AddNewProfessor(luser)).setVisible(true);
    }//GEN-LAST:event_menuAddProfessorActionPerformed

    private void menuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddStudentActionPerformed
        (new AddNewStudent(luser)).setVisible(true);
    }//GEN-LAST:event_menuAddStudentActionPerformed

    private void menuUpdateAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateAdminsActionPerformed
        (new UpdateDeleteAdmin(luser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateAdminsActionPerformed

    private void menuUpdateProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateProfessorsActionPerformed
        (new UpdateDeleteProfessor(luser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateProfessorsActionPerformed

    private void menuUpdateStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateStudentsActionPerformed
        (new UpdateDeleteStudent(luser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateStudentsActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        (new LoginForm()).setVisible(true);
        this.dispose(); // the Menu form is disposed ONLY when the currently logged in user logs out
    }//GEN-LAST:event_menuLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuAddAdmin;
    private javax.swing.JMenuItem menuAddDepartments;
    private javax.swing.JMenuItem menuAddEvents;
    private javax.swing.JMenuItem menuAddProfessor;
    private javax.swing.JMenuItem menuAddStudent;
    private javax.swing.JMenu menuAddUsers;
    private javax.swing.JMenu menuDepartment;
    private javax.swing.JMenu menuEvent;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLog;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuOrganize;
    private javax.swing.JMenu menuRegister;
    private javax.swing.JMenuItem menuUpdateAdmins;
    private javax.swing.JMenuItem menuUpdateDepartments;
    private javax.swing.JMenuItem menuUpdateEvents;
    private javax.swing.JMenuItem menuUpdateProfessors;
    private javax.swing.JMenuItem menuUpdateStudents;
    private javax.swing.JMenu menuUpdateUsers;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem menuViewDepartments;
    private javax.swing.JMenuItem menuViewEvents;
    // End of variables declaration//GEN-END:variables
}
